from enum import IntFlag, auto

class IPSocketOption(IntFlag):

    """
   Socket options
       IP_ADD_MEMBERSHIP (since Linux 1.2)
       IP_ADD_SOURCE_MEMBERSHIP (since Linux 2.4.22 / Linux 2.5.68)
       IP_BIND_ADDRESS_NO_PORT (since Linux 4.2)
       IP_BLOCK_SOURCE (since Linux 2.4.22 / 2.5.68)
       IP_DROP_MEMBERSHIP (since Linux 1.2)
       IP_DROP_SOURCE_MEMBERSHIP (since Linux 2.4.22 / 2.5.68)
       IP_FREEBIND (since Linux 2.4)
       IP_HDRINCL (since Linux 2.0)
       IP_LOCAL_PORT_RANGE (since Linux 6.3)
       IP_MSFILTER (since Linux 2.4.22 / 2.5.68)
       IP_MTU (since Linux 2.2)
       IP_MTU_DISCOVER (since Linux 2.2)
       IP_MULTICAST_ALL (since Linux 2.6.31)
       IP_MULTICAST_IF (since Linux 1.2)
       IP_MULTICAST_LOOP (since Linux 1.2)
       IP_MULTICAST_TTL (since Linux 1.2)
       IP_NODEFRAG (since Linux 2.6.36)
       IP_OPTIONS (since Linux 2.0)
       IP_PASSSEC (since Linux 2.6.17)
       IP_PKTINFO (since Linux 2.2)
       IP_RECVERR (since Linux 2.2)
       IP_RECVOPTS (since Linux 2.2)
       IP_RECVORIGDSTADDR (since Linux 2.6.29)
       IP_RECVTOS (since Linux 2.2)
       IP_RECVTTL (since Linux 2.2)
       IP_RETOPTS (since Linux 2.2)
       IP_ROUTER_ALERT (since Linux 2.2)
       IP_TOS (since Linux 1.0)
       IP_TRANSPARENT (since Linux 2.6.24)
       IP_TTL (since Linux 1.0)
       IP_UNBLOCK_SOURCE (since Linux 2.4.22 / 2.5.68)
       SO_PEERSEC (since Linux 2.6.17)
    """
    IP_ADD_MEMBERSHIP = 0x1
    IP_ADD_SOURCE_MEMBERSHIP = auto()
    IP_BIND_ADDRESS_NO_PORT = auto()
    IP_BLOCK_SOURCE = auto()
    IP_DROP_MEMBERSHIP = auto()
    IP_DROP_SOURCE_MEMBERSHIP = auto()
    IP_FREEBIND = auto()
    IP_HDRINCL = auto()
    IP_LOCAL_PORT_RANGE = auto()
    IP_MSFILTER = auto()
    IP_MTU = auto()
    IP_MTU_DISCOVER = auto()
    IP_MULTICAST_ALL = auto()
    IP_MULTICAST_IF = auto()
    IP_MULTICAST_LOOP = auto()
    IP_MULTICAST_TTL = auto()
    IP_NODEFRAG = auto()
    IP_OPTIONS = auto()
    IP_PASSSEC = auto()
    IP_PKTINFO = auto()
    IP_RECVERR = auto()
    IP_RECVOPTS = auto()
    IP_RECVORIGDSTADDR = auto()
    IP_RECVTOS = auto()
    IP_RECVTTL = auto()
    IP_RETOPTS = auto()
    IP_ROUTER_ALERT = auto()
    IP_TOS = auto()
    IP_TRANSPARENT = auto()
    IP_TTL = auto()
    IP_UNBLOCK_SOURCE = auto()
    SO_PEERSEC = auto()

class IPProtocol(IntFlag):

    IPPROTO_TCP = 1
    IPPROTO_UDP = auto()
    IPPROTO_SCTP = auto()
    IPPROTO_UDPLITE = auto()
