
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ioctlTCGETSargsCOMMA ELLIPSIS INTEGER LBRACE RBRACE TCGETSarg TCGETStagioctlTCGETSargs : fd COMMA TCGETStag COMMA TCGETStermiosfd : INTEGERTCGETStermios : LBRACE TCGETSargstring RBRACETCGETSargstring : TCGETSargTCGETSargstring : ELLIPSISTCGETSargstring : TCGETSarg TCGETSargstring'
    
_lr_action_items = {'INTEGER':([0,],[3,]),'$end':([1,7,12,],[0,-1,-3,]),'COMMA':([2,3,5,],[4,-2,6,]),'TCGETStag':([4,],[5,]),'LBRACE':([6,],[8,]),'TCGETSarg':([8,10,],[10,10,]),'ELLIPSIS':([8,10,],[11,11,]),'RBRACE':([9,10,11,13,],[12,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ioctlTCGETSargs':([0,],[1,]),'fd':([0,],[2,]),'TCGETStermios':([6,],[7,]),'TCGETSargstring':([8,10,],[9,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ioctlTCGETSargs","S'",1,None,None,None),
  ('ioctlTCGETSargs -> fd COMMA TCGETStag COMMA TCGETStermios','ioctlTCGETSargs',5,'p_ioctlTCGETSargs','parser.py',17),
  ('fd -> INTEGER','fd',1,'p_fd','parser.py',21),
  ('TCGETStermios -> LBRACE TCGETSargstring RBRACE','TCGETStermios',3,'p_TCGETStermios','parser.py',25),
  ('TCGETSargstring -> TCGETSarg','TCGETSargstring',1,'p_TCGETSargstring0','parser.py',33),
  ('TCGETSargstring -> ELLIPSIS','TCGETSargstring',1,'p_TCGETSargstring1','parser.py',37),
  ('TCGETSargstring -> TCGETSarg TCGETSargstring','TCGETSargstring',2,'p_TCGETSargstring2','parser.py',41),
]
